# Generated by Django 4.1.1 on 2022-09-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('english_title', models.CharField(max_length=200)),
                ('english_content', models.TextField(blank=True)),
                ('french_title', models.CharField(max_length=200)),
                ('french_content', models.TextField(blank=True)),
                ('is_every_appraisal', models.BooleanField(default=False)),
                ('allow_more_consent', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
